[sources]
"Bertrand" = "~/image/20*"
"Alice" = "~/image/alice/20*"
"GPhoto" = "~/gphoto/Takeout/Google Photos/Photos*"
"Wallpaper" = "~/image/wallpaper"


[destination]
host_alias = "chenal"
sizes = [1600, 800, 400]
root = 'images'